name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}

    name: SoAPy test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Create SoAPy environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: SoAPy
          environment-file: devtools/conda-envs/SoAPy.yaml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install SoAPY
        run: |
          pip install -e .
          pip install pytest

      - name: Run tests
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          pytest -v --cov=SoAPy --cov-report=xml --color=yes SoAPy/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
